// Simple converter - run with: node convert-kb.mjs
import { readFileSync, writeFileSync } from 'fs';

console.log('📖 Reading /public/knowledge-base.json...');
const jsonData = JSON.parse(readFileSync('./public/knowledge-base.json', 'utf8'));

console.log(`✅ Found ${jsonData.pageCount} pages`);
console.log('✍️  Writing to /src/knowledge-base.ts...');

const tsContent = `// Knowledge Base for CFLAR Chatbot
// This file is auto-generated by the scraper (npm run scrape)

export const knowledgeBase = ${JSON.stringify(jsonData, null, 2)};

export default knowledgeBase;
`;

writeFileSync('./src/knowledge-base.ts', tsContent, 'utf8');

console.log('✅ Conversion complete!');
console.log(`📄 /src/knowledge-base.ts now has ${jsonData.pageCount} pages`);
console.log('\nYou can now delete this script: rm convert-kb.mjs');
